stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: react-app:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker save $DOCKER_IMAGE > react-app.tar
  artifacts:
    paths:
      - react-app.tar
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - scp react-app.tar $SERVER_USER@$SERVER_IP:/tmp/react-app.tar
    - scp docker-compose.yml $SERVER_USER@$SERVER_IP:/app/docker-compose.yml
    - ssh $SERVER_USER@$SERVER_IP "
        docker load -i /tmp/react-app.tar &&
        cd /app &&
        docker-compose down &&
        docker-compose up -d
      "
  only:
    - main