deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp $SSH_PRIVATE_KEY ~/.ssh/private_key
    - chmod 600 ~/.ssh/private_key
    - ssh-add ~/.ssh/private_key
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - scp react-app.tar $SERVER_USER@$SERVER_IP:/tmp/react-app.tar
    - scp docker-compose.yml $SERVER_USER@$SERVER_IP:/app/react-app/docker-compose.yml
    - ssh $SERVER_USER@$SERVER_IP "
        docker load -i /tmp/react-app.tar &&
        cd /app/react-app &&
        docker-compose down &&
        docker-compose up -d
      "
  only:
    - master